<?php 
echo "<pre>";
// print_r($book->details->identifiers->google[0]);
// print_r(json_decode($book['details']['identifiers']['google'][0]),true);
// die;
// $google = $book->details->identifiers->google[0];

// details
?>
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title></title>
  <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'>
<link rel="stylesheet" href="/home/cedcoss/git /events_phalcon/src/app/views/index/style.css">

</head>
<body>
<!-- partial:index.partial.html -->

<div class="card mb-3">
  <?php
  // foreach($book as $key){
    ?>
  <img class="card-img-top" style="height: 328px;width: 283px;" src="https://covers.openlibrary.org/b/ISBN/<?php echo $val;?>-S.jpg" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><?php echo $book['details']['title'] ; ?></h5>
    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <p class="card-text"><small class="text-muted">Publisher  <strong><?php echo $book['details']['publishers'][0] ; ?></strong></small></p>
    <p class="card-text"><small class="text-muted">Published Date  <?php echo $book['details']['publish_date'] ; ?></small></p>
    <p class="card-text"><small class="text-muted">Published Date  <?php echo $book['details']['description'] ; ?></small></p>
    <p class="card-text"><small class="text-muted">Last updated <?php echo $book['details']['last_modified']['value'] ; ?> </small></p>
    <p class="card-text"><small class="text-muted">Last updated <?php 
    if(!empty($book['details']['identifiers']['google'][0])){
      $google = urlencode($book['details']['identifiers']['google'][0]);
      ?>
     <p> <a href="https://www.google.co.in/books/edition/Slow_reading/<?php echo $book['details']['identifiers']['google'][0] ?>?hl=en"> Goggle Link </a></p>
  <?php }else{
    ?> <br>Not In google<?php

  }
    ?> </small>

    <!-- $book->details->identifiers->google[0] -->
  </div>
  <?php  ?>
</div>
</section>
<!-- partial -->
  
</body>
</html>
